# Generated by Django 5.2.3 on 2025-06-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupCreationRequest',
        ),
    ]
