# Generated by Django 5.2.3 on 2025-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_creation_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinvite',
            options={'verbose_name': 'Group Invite', 'verbose_name_plural': 'Group Invites'},
        ),
        migrations.RemoveIndex(
            model_name='groupinvite',
            name='groups_grou_group_i_bcb57e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='group',
            name='invite_token',
        ),
        migrations.RemoveField(
            model_name='group',
            name='invite_token_expiry',
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='token',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='uses',
        ),
    ]
