# Generated by Django 5.2.3 on 2025-06-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groupinvite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
