# Generated by Django 5.2.3 on 2025-06-21 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group View',
                'verbose_name_plural': 'Group Views',
                'indexes': [models.Index(fields=['group', 'user'], name='groups_grou_group_i_66b274_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
