export const ROUTES = {
    landing: '/',
    home: '/home',
    register: '/register',
    login: '/login',
    dashboard: '/dashboard',
    profile: '/profile',
    settings: '/settings',
    communities: '/communities',
    usergroups:'/usergroups',
    jobs: '/jobs',
    blog: '/blog',
    groups: '/groups',
    about: '/about',
    contact: '/contact',
    privacy: '/privacy',
    terms: '/terms',
    cookies: '/cookies',
    guidelines: '/guidelines',
    verify_email_sent: '/verify-email-sent',
    verify_email: '/verify-email/:uidb64/:token',
    password_reset_request: '/reset-password',
    password_reset_confirm: '/reset-password/:uid/:token',
}

export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8001'; 