# Generated by Django 5.2.3 on 2025-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_topic_customuser_has_completed_onboarding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='icon',
        ),
    ]
